services:
  hazelcast-2:
    image: hazelcast/hazelcast:5.3
    restart: unless-stopped
    environment:
      HAZELCAST_CONFIG: hazelcast.xml
      HZ_NETWORK_PUBLICADDRESS: 10.26.14.242:5701
    ports:
      - "5701:5701"
    volumes:
      - ./hazelcast-pc3.xml:/opt/hazelcast/hazelcast.xml:ro

  crawler-1:
    image: stage3/crawler:desktop
    restart: unless-stopped
    environment:
      PORT: "7007"
      CRAWLER_ID: "1"
      NUM_CRAWLERS: "3"
      DATALAKE_PATH: /data
      NODE_URL: http://10.26.14.242:7007
      CRAWLER_PEERS: http://10.26.14.243:7007,http://10.26.14.245:7007
      REPLICATION_FACTOR: "3"
      BROKER_URL: tcp://10.26.14.244:61616
      INGESTION_QUEUE: document.ingested
    ports:
      - "7007:7007"
    volumes:
      - crawler1-data:/data

  search-2:
    image: stage3/search:desktop
    restart: unless-stopped
    environment:
      PORT: "7003"
      MONGO_URI: mongodb://10.26.14.246:27017
      MONGO_DB: searchengine
      MONGO_COLLECTION: books
      HZ_CLUSTER_NAME: search-cluster
      HZ_MEMBERS: 10.26.14.243:5701,10.26.14.242:5701,10.26.14.245:5701
    ports:
      - "7003:7003"

volumes:
  crawler1-data:
